### ISSUE TITLE
Sprayer Animation Bug in Multiplayer

### ISSUE THREAD

**Issue by timmi4026** [RivalAUT/FS19_SprayerSectionControl#1]
Hello,
I have a problem with Multiplayer (DedicServer). The Sprayer Animation does not correctly work on a Server. 
You don´t see any Animations on the Spray Nozzles. In Single Play it works correctly.

Best Regards   Timmi

**Comment by RivalAUT** [comment]
Try it with V 0.2.0.0, it should work now.
