### ISSUE TITLE
Rubicon T

### ISSUE THREAD

**Issue by bauerwilhelm** [RivalAUT/FS19_SprayerSectionControl#11]
Helloo:

This is a so fantastic mod, I love it! Not just because it adds realism to the game but saves me some money! :D

Now for the problem: I followed every little step from Kederk Farms' YT video and in the end I found out, that the Rubicon T (by Sam) has just seven effectNodes (two of them behind the wheels) but I planned in eleven workareas, positioned between the nozzles. Is it possible to do it like that anyways or will I have to change the thing to fit the seven/five original effectNodes?

**Comment by RivalAUT** [comment]
Hi, if you want eleven workareas you need to edit the effectNodes so that you have eleven of them.

**Comment by bauerwilhelm** [comment]
What a fast answer, wow!

Does that need to be done in Giants Editor and xml or will xml editing be enough? I started modding 2 hours ago haha

**Comment by RivalAUT** [comment]
Might be too much for you then... You'd have to search for a single nozzle effect and replace every one in the i3d (Giants Editor)

**Comment by bauerwilhelm** [comment]
Yep, I'm out than. But thanks for your help anyways. I'll try on other mods then, I really need it in big scales :)

**Comment by bauerwilhelm** [comment]
Idk am I dumb? What did I do wrong know?

log

EDIT: I may not be dumb, but very inexperienced in coding. Seems like capital letters in the wrong place fuck shit up...
