### ISSUE TITLE
Performance Probleme

### ISSUE THREAD

**Issue by derHaggie** [RivalAUT/FS19_SprayerSectionControl#12]
Guten Tag, 
ich habe mir die Horsch Leeb auf Einzeldüsenabschaltung (144 TB's) umgebaut. Funktioniert grundsätzlich auch supergut.
Ich hab aber das Problem, wenn ich PSM spritzen möchte habe ich extreme FPS Einbrüche (von konstant 60 auf 15 FPS). Bei Flüssigdünger ist das Problem nicht. 
Die Log zeigt keine fehler an und an anderen Mods liegt es auch nicht.

Bin über jede Hilfe dankbar.

**Comment by RivalAUT** [comment]
Hi,
könntest du mir die Spritze privat zukommen lassen damit ich das testen und analysieren kann? Auf jeden Fall komisch, dass es nur bei Herbizid und nicht bei Dünger auftritt.
LG

**Comment by derHaggie** [comment]
ja klar, kein problem 
https://www.dropbox.com/s/o9nn85z0wugdpmu/FS19_Horsch_Leeb_PT350.zip?dl=0

**Comment by RivalAUT** [comment]
Sorry, bin noch nicht dazu gekommen und die Datei wurde schon gelöscht, könntest du die vielleicht nochmal kurz hochladen?

**Comment by derHaggie** [comment]
https://www.dropbox.com/s/61xl370f8ngy5uh/FS19_Horsch_Leeb_PT350.zip?dl=0
sollte wieder gehen

**Comment by RivalAUT** [comment]
Danke, ist heruntergeladen, jetzt kannst du es wieder offline nehmen ;)

**Comment by RivalAUT** [comment]
Die Performanceeinbrüche scheinen vom LS selbst ausgelöst zu werden, denn auch ohne dem SectionControl Script sinken die FPS stark ab. Anscheinend kommt der nicht mit so vielen workAreas gleichzeitig zurecht, komischerweise aber auch nur bei Herbizide..
