### ISSUE TITLE
Question : Is weeds presence testing available ?

### ISSUE THREAD

**Issue by Lactic68** [RivalAUT/FS19_SprayerSectionControl#13]
Hi,
Thank you for your mod this add quite some cool features to sprayer. I was just wondering if it is possible to test weeds presence instead of testing if the area was already spread ?

Idea is to take a step into precision farming for only spraying where it detects weeds.

**Comment by RivalAUT** [comment]
This was the case in earlier versions and has been changed due to requests for the possibility of pre-emergence spraying.
It's currently not planned to change this back again.

**Comment by Lactic68** [comment]
Thank you for your quick answer and well I suppose it is not possible to add a toogle for this kind of functionality.

By the way is an earlier version available if we would like automatic mode to only detect weeds ?

**Comment by RivalAUT** [comment]
You can change line 260 in SprayerSectionControl.lua from
`self:setAIFruitRequirements(g_fruitTypeManager:getFruitTypeByName("weed").index, 0, 2)`
to
`self:setAIFruitRequirements(g_fruitTypeManager:getFruitTypeByName("weed").index, 1, 2)`
then it only detects visible weed.

**Comment by Lactic68** [comment]
Fantastic Rival, you are awesome ! 
Thank you very much for your quick feedback. This will make our farm more environnemental friendly by only spraying where it needs to be (precision farming).
Have a nice day

**Comment by Lactic68** [comment]
Hi Rival,

I just downloaded your recent updated version 0.3.1.0 and I can't find the old code
`self:setAIFruitRequirements(g_fruitTypeManager:getFruitTypeByName("weed").index, 0, 2)`

that I have to replace to this : 
`self:setAIFruitRequirements(g_fruitTypeManager:getFruitTypeByName("weed").index, 1, 2)`

Does it mean that you new version is now only spraying when it detects weeds ?

**Comment by RivalAUT** [comment]
Ah yes, the code has changed, it's now in line 146. Change this:
`spec.herbicideQuery:addRequiredCropType(g_currentMission.fruits[desc.index].id, 1, 3, desc.startStateChannel, desc.numStateChannels, g_currentMission.terrainDetailTypeFirstChannel, g_currentMission.terrainDetailTypeNumChannels)`
to this:
`spec.herbicideQuery:addRequiredCropType(g_currentMission.fruits[desc.index].id, 2, 3, desc.startStateChannel, desc.numStateChannels, g_currentMission.terrainDetailTypeFirstChannel, g_currentMission.terrainDetailTypeNumChannels)`
I have not tested this change, but i think thats it.

**Comment by Lactic68** [comment]
As always, thanks for your quick and accurate answer 👍🏻
