### ISSUE TITLE
Section Control für Güllefässer

### ISSUE THREAD

**Issue by Kalle639** [RivalAUT/FS19_SprayerSectionControl#14]
Hallo,
ich habe Section Control in diverse Spritzen eingebaut. Es funktioniert super möchte nicht mehr ohne Spritzen. Ich habe versucht es in Güllefässer einzubauen aber es funktioniert nicht. Kannst Du Section Control ach für Güllefässer machen?
Danke!

**Comment by RivalAUT** [comment]
Ich werd mir das mal für die nächste Version merken, sollte kein großer Aufwand sein.

**Comment by RivalAUT** [comment]
Die aktuelle Version unterstützt Güllefässer schon, lediglich das HUD könnte etwas verbuggt sein.

**Comment by Kalle639** [comment]
Cool Danke!

**Comment by ernstel** [comment]
Guten Abend! Ich hab mir das in das Schleppschlauch GlideFix15 eingebaut, hab aber selber das Problem das das Hud nicht 
sauber anzeigt ,bzw. schalten die Teilbreiten nicht richtig ab.
Nun bin ich nicht sicher ob die LUA überhaupt darauf ausgelegt ist, Anbaugeräte die mit "V" abgelassen werden.
Das Patikel schaltet leider nicht ab beim anheben.

Ist da von deiner Seite noch geplant Anbaugeräte die angekuppelt werden mit Section Control auszurüsten?

Mfg ernstel

**Comment by Kalle639** [comment]
Ich habe es in den GlideFix15 aus dem Holmer Gülle Pack eingebaut, es funktioniert wie es soll.

**Comment by ernstel** [comment]
Okay Kalle, das ist schon mal gut zu wissen. Dann muss ich mal fragen:
Hast du 9 workArea Id´s ?
Hast du in den  workAreas auch die  groundReferenceNode index="1"/> mit drin? ohne die gibt es Logfehler
Das ich mir die xml komplett anschauen kann ist wohl nicht drin, oder?  Da ich den Fehler meinerseits nicht finde, versuche ich es aber weiter

Nutzt du dafür die 0.3.0.1 ?

**Comment by Kalle639** [comment]
ich habe 9 workAreas und ich habe die v0.3.1.0  Hier ein Beispiel für eine WorkArea. Schau dir genau die Reihenfolge der effectNodeId an (1/2/3/4/5/9/8/7/6)

 <workArea type="sprayer" functionName="processSprayerArea" disableBackwards="false" requiresGroundContact="false" >
            <area startNode="workAreaStart1" widthNode="workAreaWidth1" heightNode="workAreaHeight1" />
        </workArea>

<sections>
			<section workingWidth="2.2" workAreaId="1" effectNodeId="1" testAreaStartNode="testAreaStart1" 
                           testAreaWidthNode="testAreaWidth1" testAreaHeightNode="workAreaHeight1" />

        <i3dMapping id="workAreaStart1" node="0>0|2|0|1|12|0|0" />
        <i3dMapping id="workAreaWidth1" node="0>0|2|0|1|12|0|1" />
        <i3dMapping id="workAreaHeight1" node="0>0|2|0|1|12|0|2" />
        <i3dMapping id="testAreaStart1" node="0>0|2|0|1|12|0|3" />
	<i3dMapping id="testAreaWidth1" node="0>0|2|0|1|12|0|4" />

**Comment by RivalAUT** [comment]
0.3.1.0 ist die Version mit der das HUD gefixt wurde. Bei der 0.3.0.1 ist es klar dass es nicht richtig geht.

**Comment by ernstel** [comment]
Nabend! Ich hab mal jetzt div, Schleppschläuche versucht das ein zu bauen, als Mod oder Güllefässer mit Schleppschlauch, Fazit:         
In keinem bekomme ich es hin das mit der Version 0.3.1.0 mir das Hud angezeigt wird. Hab mir das vom FS19_VeenhuisPremiumIntegral30000 der in der Zip ist abgeschaut. Wahrscheinlich sitzt das Problem vorm Monitor, oder ich hab das Prinzip immer noch nicht verstanden. Ich mache jetzt erstmal Pause hier, vielleicht wird das Schleppschlauch Gestänge hier ja noch mal Freigegeben. Trotzdem, super Sache, ich wünsch euch was.

**Comment by Kalle639** [comment]
In den GlideFix15 aus dem Holmer Gülle Pack habe ich es hin bekommen. Aber der SBH4_36 funktioniert bei mir auch nicht, gleiches Problem Hud wird nicht angezeigt.

**Comment by RivalAUT** [comment]
Stimmt, beim SBH4 ist mir das auch aufgefallen, dort wird vom LS die onDraw Funktion nicht aufgerufen. Vermutlich weil es nicht direkt am Traktor hängt...

**Comment by Kalle639** [comment]
Kannst du das ändern?

**Comment by RivalAUT** [comment]
Zurzeit mal nicht geplant. Vielleicht später mal.

**Comment by Kalle639** [comment]
Erstmal sehen was bei Giants so geplant ist (Precision Farming) usw.

**Comment by ernstel** [comment]
Nabend zusammen! kurzes Feedback: Komme grad vom Test des GlideFix15,Teilbreitenschaltung funktioniert bei mir nun auch. Alles einmal neu gemacht, Nutze die Version 0.2.0.0
Mit der Version 0.3.1.0 bekomme ich das Hud nicht ins Game. 
Meine Geduld hat sich ausgezahlt ,lol!  Haut rein Leute und danke für dieses Script!

**Comment by derHaggie** [comment]
Das ist mir auch schon aufgefallen, die Standart Güllefässer zeigen das Hud nicht an, wenn du das SBH4 36 aber an Modfässer hängst, funktioniert es problemlos (nutze das Kumm vom Modhub gerne). Selbes gilt wenn man Arbeitsbreiten einbaut (hab es mir umgebaut das es in verschiedene Arbeitsbreiten zu klappen ist, wie in real)
Ich weiß auch nicht warum, aber einfach Modfässer nehmen, dann sollte das problem gehoben sein
