### ISSUE TITLE
Courseplay issue with my modification

### ISSUE THREAD

**Issue by polosubtil** [RivalAUT/FS19_SprayerSectionControl#16]
Hi Rival,

Amazing mode, thanks a lot for that. I was actually looking for something like that for a while.
I did a modification on a trailed Horsch sprayer from ModHub : https://www.farming-simulator.com/mod.php?lang=fr&country=fr&mod_id=166920&title=fs2019
I did 37 sections in auto and 11 in manual using the GroupID.
Not sure how but I broke something along the way as it doesn't work with Courseplay anymore (it works in manual) => The sprayer doesn't unfold at the start of the course and if it is unfolded manually, it doesn't start spraying. I have to start spraying manually and then start the course so it "works", but it doesn't stop spraying at the end of a row (which is fine as the section control does the job ;) )
Please see below the XML, maybe you can tell me what I have done wrong here, hoping this is not an issue in the i3d file

[horsch.zip](https://github.com/RivalAUT/FS19_SprayerSectionControl/files/5471878/horsch.zip)

**Comment by derHaggie** [comment]
Hey,
the XML looks fine to me, maybe it is a i3d problem, i have an idea what the issue is, but without i3d it is hard to tell. maybe you can send i3d to?

**Comment by polosubtil** [comment]
Hi @derHaggie 
Off course, no problem
[leeb5lt.zip](https://github.com/RivalAUT/FS19_SprayerSectionControl/files/5492034/leeb5lt.zip)

**Comment by RivalAUT** [comment]
The indices for the AI areaMarkers are wrong. This might cause the problem.
It should be 
`<areaMarkers leftNode="0>0|0|0|0|8|0|0" rightNode="0>0|0|0|0|8|0|1" backNode="0>0|0|0|0|8|0|2" />`

**Comment by polosubtil** [comment]
Thanks for the tip, I will try tonight

**Comment by polosubtil** [comment]
It works like a charm, thank you very much guys, you rock !!!!!!
