### ISSUE TITLE
HUD modifications

### ISSUE THREAD

**Issue by delawarehunter** [RivalAUT/FS19_SprayerSectionControl#17]
I'd like to make the HUD smaller and move it to a different location on the screen.  How would I go about doing that?

**Comment by RivalAUT** [comment]
SprayerSectionControl.lua, line 173, reduce hudScale to make the HUD smaller.
Lines 193 and 194 are for X and Y coordinates on the screen.

**Comment by delawarehunter** [comment]
Awesome!  Thanks for the quick reply.  Here is where I moved mine:
![SSCHud](https://user-images.githubusercontent.com/6019702/99190055-64ec7c00-2732-11eb-93d3-c422e7f8da89.jpg)

My changes: 
(line 173) hudScale = 0.20
(line 194) BaseY = 0.85
