### ISSUE TITLE
Stuck in Section Control Hud

### ISSUE THREAD

**Issue by SteveMCAU** [RivalAUT/FS19_SprayerSectionControl#18]
I had the JD4940 spraying a field using course play i selected the mouse wheel button to enter the Section Control Hud, i then right clicked the mouse opening the Courseplay Hud, when I closed the course play Hud I was stick with no working HUD and no key combination would give any response i.e. ESC, TAB , CTRL + G or CTRL + S, I had the close FS19 with task manager
![fsScreen_2020_11_28_00_08_06](https://user-images.githubusercontent.com/38418481/100452764-e4545500-310d-11eb-8bd6-68cc3fd21013.png)

[log.txt](https://github.com/RivalAUT/FS19_SprayerSectionControl/files/5607948/log.txt)

**Comment by polosubtil** [comment]
I had that too and the only option I found was to turn off the option to open Courseplay using the mouse right clic
