### ISSUE TITLE
Rate control

### ISSUE THREAD

**Issue by polosubtil** [RivalAUT/FS19_SprayerSectionControl#19]
Hi Lukas,

I was wondering if it could be OK to have as sort of rate controller for speed on top of the section control ?
I was thinking (I tried already but I would like to ask your thoughts on that) to have something like that
https://github.com/polosubtil/FS19_SprayerSectionControl/blob/a39921b12c9ef4c812bdf283e57cd39eeef0107a/SprayerSectionControl.lua#L453

Do you think it is acceptable ? I only tested it on my sprayer (Horsch) but I can do more if you think it's usable in your code

Thanks mate, and terrific job so far, I love that mod

Polo

**Comment by RivalAUT** [comment]
Thats a good feature. I will add that, thanks.
