### ISSUE TITLE
lost visibility of HUD with V0.4.0.5  

### ISSUE THREAD

**Issue by mrPassion78** [RivalAUT/FS19_SprayerSectionControl#25]
Hi there, i have seen that i have lost the HUD completely with the new update.
The log shows no errors, and the sprayers spray fine.

The only thing visible is the words AUTOMATIC MODE or MANUAL MODE

the rest is all gone.

i`m going to rollback the mod to the previous version to see what happens with that one.
i`ll drop a screenshot in here to of it
![fsScreen_2020_12_17_20_51_44](https://user-images.githubusercontent.com/40406761/102536330-c2654700-40a9-11eb-88bd-0e4b7f36f173.png)

**Comment by mrPassion78** [comment]
so got though testing and for me the version V 0.4.0.0 is working again, the V 0.4.0.3 gives the same problem.
the key combos Lshift-B made the words disappear and with Lctrl-B i just got the mouse back but no further HUD.
The version 0.4.0.0 is fine, and the HUD is visible
below the screenshot of the V 0.4.0.0
![fsScreen_2020_12_17_21_11_33](https://user-images.githubusercontent.com/40406761/102538401-81226680-40ac-11eb-9e48-07b3fe414273.png)

**Comment by RivalAUT** [comment]
Try it again with 0.4.0.6 please, i don't know what is causing this problem. I tested it with a few different sprayers and manure barrels (in singleplayer and on a dedicated server) and didn't have this problem.

**Comment by mrPassion78** [comment]
hi there, sorry for the late reaction, i`m going to try the 0.4.0.6, and report back, but sins you cant recreate it, my best guess will be that i have a mod conflict. 
i will get back to you. thnx in advance

**Comment by mrPassion78** [comment]
hi there..i have tested it, and still the same result, BUT..i am sure that it will be a mod clash,  sins i have..( and i just saw the number ) 😨 🤣 
377 mods active in my save game as well in my testing save game.. they all work fine without errors, just have to go and find the one(s) that course trouble with SSC...
But that..will take a few days.. LOL. 🤣 
If i find what mod it is, i will let you know 👍🏻

**Comment by mrPassion78** [comment]
i am happy to report that i have found the mod, that has a conflict with the SSC, without any errors or warnings in the log.
its  FS19_hudSmartShade [https://www.farming-simulator.com/mod.php?lang=en&country=nl&mod_id=128515&title=fs2019](url)
 <author>ViperGTS96</author>
  
    <version>1.6.0.0</version>
with this mod out, the SSC works again just fine.. it always did work, just nod the hud..
but the HUD mod is out, and i can enjoy the SSC mod again.. thnx for the mod and the testing

**Comment by RivalAUT** [comment]
Now it should work with the hudSmartShade mod too.

**Comment by mrPassion78** [comment]
> Now it should work with the hudSmartShade mod too.

i will try it tomorrow..thnx for the FAST fix 😄

**Comment by mrPassion78** [comment]
Dear Rival, you fixed it.. awesome.. thnx so much. 

thnx for the quick fix
