### ISSUE TITLE
DLC Kverneland IXTER B18 section control ready ?

### ISSUE THREAD

**Issue by Lactic68** [RivalAUT/FS19_SprayerSectionControl#28]
Hi Rival,
The question should have been already asked but is there a way to adapt your section control to the DLC Kverneland Sprayers (like Ixter B18) ?

**Comment by RivalAUT** [comment]
Hi,

its not possible without unpacking the DLC and editing it manually. And the configurable spraying width is not supported at the moment too.

**Comment by Lactic68** [comment]
Ok, thank you Rival
