### ISSUE TITLE
AI Worker

### ISSUE THREAD

**Issue by L2KPerma** [RivalAUT/FS19_SprayerSectionControl#3]
Released my edit to the R4045 with the script shortly after it came out and have had two reports in similar nature regarding AI workers when the script is active.

Transcript below of what one of the reporters found trying to find the issue.

> ok i think i figured it out. If you start yourself on half a pass then switch to ai thats when its stuck to lets say half the jets even if it comes to a spot that hasn’t been sprayed at all. To get out of that stuck position, you have to take over the ai, go to a spot that hasnt been sprayed at all spray a bit then you can bring back the ai to half a pass and it will work (i realized in ai the sectionnal control doesnt work its all the jets)

**Comment by RivalAUT** [comment]
Ah... yes, the control is disabled while AI is active, although turned off section won't automatically be activated when starting AI.
I will fix that in the next version.

**Comment by RivalAUT** [comment]
Fixed in version 0.1.2.0
