### ISSUE TITLE
Case Trident Conversion :: Spray animation continues

### ISSUE THREAD

**Issue by Jaiimez** [RivalAUT/FS19_SprayerSectionControl#4]
Hello, just downloaded the mod, and converted the Case Trident downloaded off a 3rd party mod hub.

For the most part, it seems to be working, i've noticed when I drive over patches i've already sprayed, my spray usage goes down to 0, so mechanics side of it is working, however, the animation continues, i've got a small area on the left hand boom about 2/3rd's of the way down that never seems to spray (animation) but the rest of it seems to be permanantly on, even if the sprayer isn't actually applying any fertilizer, you got any clue where I may have gone wrong with the conversion, i'll upload what I have currently.

**Comment by Jaiimez** [comment]
The modified .zip with my changes can be found here, ill upload a video tomorrow.
https://1drv.ms/u/s!AjQVdRgcs56OhLU__173uNFBtuP12g

Update: I have realised this Trident is potentially an unauthorised ripoff/reskin of Perma's R4045, i'm waiting to hear from Perma first if this reskin had his blessing before I do anymore work as I don't want to support thieves.

**Comment by RivalAUT** [comment]
Looks like you forgot to change the effectNodeId's in the spayerSectionControl part. In your mod there are only 5 effect nodes stated, but in total there are 16 effectNodes (line 95-112). Adjust this and it should work properly.

**Comment by Jaiimez** [comment]
> Looks like you forgot to change the effectNodeId's in the spayerSectionControl part. In your mod there are only 5 effect nodes stated, but in total there are 16 effectNodes (line 95-112). Adjust this and it should work properly.

Thank you for your response, I spoke with Perma who said it wasn't his mod originally anyway so doesn't have an issue with it, I actually just ended up using his setup for the R4045 since it's just a reskin anyway.
