### ISSUE TITLE
automatic mode before weed emergence

### ISSUE THREAD

**Issue by foreverls19** [RivalAUT/FS19_SprayerSectionControl#6]
Hello,
Automatic mode works with herbicide only when weeds have grown - the section is switched off when weeds are not visible. Spraying before emergence is only possible in manual mode.
Can you change that somewhere that spraying works in automatic mode before weed emergence.

mfg

**Comment by RivalAUT** [comment]
Hi.

Das geht leider nicht. Vorauflaufbehandlung geht nur im manuellen Modus (dafür gibts ja jetzt das HUD), man kann nämlich nicht abfragen ob das Feld bereits gespritzt wurde oder nicht, zumindest ist mir kein Weg bekannt. Und wenn man das außer Kraft setzt braucht man auch keine Teilbreiten mehr weil alles immer aktiv ist ;)

LG

**Comment by foreverls19** [comment]
Hallo,
Vielleicht hilft dir das weiter
https://forum.giants-software.com/viewtopic.php?t=141369

mfg

**Comment by RivalAUT** [comment]
Geht. Lösung war einfacher als gedacht :)
