### ISSUE TITLE
lua Fehler auf dem Server.

### ISSUE THREAD

**Issue by timmi4026** [RivalAUT/FS19_SprayerSectionControl#7]
Hi, habe das Update drauf und jetzt kommen wärend ich Herbizid sprühe folgender Callstack
2020-08-09 21:05 C:/Users/Herbe/Documents/My Games/FarmingSimulator2019/Lakeland Vale2/FS19_SprayerSectionControl/SprayerSectionControl.lua:345: attempt to index field 'buttons' (a nil value)
2020-08-09 21:05 Error: Running LUA method 'update'.
2020-08-09 21:05 C:/Users/Herbe/Documents/My Games/FarmingSimulator2019/Lakeland Vale2/FS19_SprayerSectionControl/SprayerSectionControl.lua:330: attempt to index field 'buttons' (a nil value)
2020-08-09 21:05 C:/Users/Herbe/Documents/My Games/FarmingSimulator2019/Lakeland Vale2/FS19_SprayerSectionControl/SprayerSectionControl.lua:316: attempt to index field 'buttons' (a nil value)

Sprayer steht auf automatik.

LG TImmi

**Comment by timmi4026** [comment]
Was mir noch zusätzlich aufgefallen ist wenn man im automodus  (düsen gelb) im hud das gerät anschaltet wechseln sie auf rot, schalte ich das gerät wieder aus bleiben sie rot. Kann das evtl mit dem callstacks zu tun haben ? Wird das Problem noch behoben ?

**Comment by RivalAUT** [comment]
Ja, hat mit den Fehlern zu tun. Ich werde im nächsten Update das ganze HUD nochmal neu scripten.

**Comment by timmi4026** [comment]
Ok sehr gut, vllt solltest Du wissen das ist mir grad aufgefallen, wenn die erste Düngerstufe auf dem Feld ist hat man im Multiplayer bei der 2ten keine sprayer Animation mehr. Aber im manuellen Modus kommt die animation. Bei Automatik bleiben auch die Segmente rot. Siehe Fotos
https://prnt.sc/u1h36u
https://prnt.sc/u1hafs

**Comment by RivalAUT** [comment]
Bitte nochmal testen mit v0.3 ob es noch immer auftritt.

**Comment by timmi4026** [comment]
mach ich gleich danke dir
kann man dich auf einen discord oder ts sprechen ?

**Comment by timmi4026** [comment]
So, Die lua Fehler scheinen auf dem Server weg zu sein, aber der Wechsel von gelben Düsen zu grün geht auch, nur wenn ich auf dem Feld unterwegs abschalte gehen die auf gelb, komme ich aber auf ein schon vorhandenes gesprühtes stück und ich schalte ab dann bleiben sie rot, das passiert auch wenn ich sie vor dem Feld an und wieder aus mache. sie gehen nur dann auf gelb zurück wenn ich auf dem Feld stehe und ausmache. Der Effekt ist bei voller anzahl düsen genau der selbe auch wenn nicht alle Düsen an sind .

**Comment by timmi4026** [comment]
Guten Morgen, nochmal ein Nachtrag, also Lua Fehler konnten wir bisher keine mehr erkennen, aber uns ist durch Zufall aufgefallen das wenn in der Spritze Herbizid drin ist und man nach dem Spritzen auf Dünger wechselt mit dem gleichen Gerät keine Sprayer Animation mehr vorhanden ist. Das Feld wird gedüngt nur mal sieht den Sprüheffekt nicht an den Düsen.
