### ISSUE TITLE
Lua Error on load

### ISSUE THREAD

**Issue by L2KPerma** [RivalAUT/FS19_SprayerSectionControl#8]
No new mods since I last played on this save (last night), received the following error when loading my save; `Error: Running Lua method ‘loadSharedI3DFileFinished’.
C:/Users/..../SprayerSectionControl/SprayerSectionControl.lua:345: attempt to index field ‘buttons’ (a nil value)`

Not sure of the cause but disabling section control, loaded in fine, saved the game, reactivated section control and loaded back in fine. From the lua, seems it might be a small bug in the hud code potentially.

**Comment by RivalAUT** [comment]
Should be fixed with v0.3, please let me know if it happens again.
