### ISSUE TITLE
Maximale Anzahl an WorkingAreas limitiert?

### ISSUE THREAD

**Issue by rooftopbbq** [RivalAUT/FS19_SprayerSectionControl#9]
Hi,

ich habe eine Damann Spritze (36m) die hat von Haus aus 9 Working Areas, aber die Effekte sind einzeln (70 Stück).
Nun möchte ich gerne dass jede Düse EINZELN geschaltet wird. Habe die Working Areas von 9 auf 70 "umgebaut".
Nun habe ich das Problem dass er im HUD leider die einzelnen Düsen nicht "erkennt" bzw korrekt anzeigt.
Gibt es dazu in einem kommenden Update Abhilfe?

**Comment by RivalAUT** [comment]
Nein, im HUD werden nur ganze Gestänge-Teile als Teilbreiten angezeigt. Eine Einzeldüsenschaltung wird nicht unterstützt. Im HUD werden maximal 13 Teile angezeigt.

**Comment by derHaggie** [comment]
Ich hab das selbe Projekt, allerdings bau ich mir grad die Horsch Leeb vom Horschpack um und die hat 140 Teilbreiten. jetzt habe ich zum testen erstmal "nur" 30 eingetragen, sie schalten auch richtig, aber jedesmal wenn eine TB sich ausschaltet: 
Error: Running LUA method 'update'.
Zu dem Hud: wäre es möglich im Script einzubauen das man Gruppen definieren kann? sodass man z.b beispiel bei den section einträgen optinal hinschreibt Group="1"

**Comment by RivalAUT** [comment]
Das ist ne gute Idee. Werd ich mir notieren.

**Comment by RivalAUT** [comment]
Gruppierungen sind jetzt mit v0.3 möglich. Siehe Readme.
